declare namespace Dict {
  export interface Dictionaries {
    'header-navbar': {
      'About YJM': string;
      'Patron & Board of Directories': string;
      'Supporting Staff': string;
      'Our Aspiration': string;
      'Our Future': string;
      'Our Activities': string;
      'Promoting Health': string;
      'Research - The Heart of A Revolution': string;
      'CPR (Cardio Pulmonary Resuscitation)': string;
      'Friends of the Foundation': string;
      'How You Can Help': string;
      'You Can Make A Difference': string;

      Facilities: string;
      'Hall Rental': string;
      'Halway House': string;

      'Health Articles': string;
      'How Does the Human Heart Work?': string;
      'Four Ways to Prevent Heart Attack': string;
      'Heart Disease Warning': string;
      'How Does Exercise Impact Weight Loss': string;
      'Heart Basics': string;
      'Steps to Better Health': string;
      'Tobacco and Your Health': string;
      'Heart Attack': string;
      'Heart Disease - Not somebody else business': string;
      'Arrhythmias and Sudden Cardiac Death': string;
      'Inherited Cholesterol Disorder': string;

      Activities: string;
      'Photo Gallery - Albums': string;
      'CPR - Course Performa': string;
      'AXA Hearts in Action Run 2020': string;
      'Walk A Million Miles 2020': string;
      'World Heart Day': string;
      'World Heart Day 2014': string;
      'World Heart Day 2013': string;
      'World Heart Day 2012': string;
      'World Heart Day 2011': string;
      'World Heart Day 2010': string;
      'World Heart Day 2009': string;
      'Go Red For Women': string;

      Bulletin: string;
      'YJM News': string;
      'Useful Links': string;

      'Contact Us': string;
      Membership: string;
      Donation: string;
    };
    'news-bulletin': {
      'News Bulletin': string;
      Description: string;
    };
    'change-lifestyle': {
      'Change Lifestyle': string;
      Description: string;
    };
    cpr: {
      'CPR (Cardio Pulmonary Resuscitation)': string;
      Description: string;
    };
    video: {
      'Video Articles': string;
    };
    'about-YJM': {
      title: string;
      subtitle: string;
      description: string;
    };
    'board-of-directories': {
      title: string;
    };
    'supporting-staff': {
      title: string;
    };
    'our-aspiration': {
      title: string;
      description: string;
      'important-areas': string;
      research: string;
      'research-description': string;
      'public-education': string;
      'public-education-description': string;
      'professional-education': string;
      'professional-education-description': string;
      rehabilitation: string;
      'rehabilitation-description': string;
      'public-service': string;
      'public-service-description': string;
    };
    'our-future': {
      title: string;
      description: string;
      'cardiac-rehabilitation-training': string;
      'cardiac-rehabilitation-training-description': string;
      'expand-cardiac-rehab-support': string;
      'expand-cardiac-rehab-support-description': string;
      'support-heart-health-programs': string;
      'support-heart-health-programs-description': string;
      'promote-healthy-lifestyles-in-schools': string;
      'promote-healthy-lifestyles-in-schools-description': string;
    };
    'our-activities': {
      title: string;
      description: string;
    };
    'promoting-health': {
      title: string;
      description: string;
    };
    'research-heart-of-revolution': {
      title: string;
      description: string;
      'foundation-supported-research-current': string;
      'foundation-supported-research-current-one': string;
      'foundation-supported-research-current-one-description': string;
      'foundation-supported-research-current-two': string;
      'foundation-supported-research-current-two-description': string;
      'foundation-supported-research-current-three': string;
      'foundation-supported-research-current-three-description': string;
      'foundation-supported-research-past': string;
      'foundation-supported-research-past-one': string;
      'foundation-supported-research-past-one-description': string;
      'foundation-supported-research-past-two': string;
      'foundation-supported-research-past-two-description': string;
      'foundation-supported-research-past-three': string;
      'foundation-supported-research-past-three-description': string;
      'foundation-supported-research-past-four': string;
      'foundation-supported-research-past-four-description': string;
      'foundation-supported-research-past-five': string;
      'foundation-supported-research-past-five-description': string;
      'foundation-supported-research-past-six': string;
      'foundation-supported-research-past-six-description': string;
      'foundation-supported-research-past-seven': string;
      'foundation-supported-research-past-seven-description': string;
      'foundation-supported-research-past-eight': string;
      'foundation-supported-research-past-eight-description': string;
      'foundation-supported-research-past-nine': string;
      'foundation-supported-research-past-nine-description': string;
      'foundation-supported-research-past-ten': string;
      'foundation-supported-research-past-ten-description': string;
      'foundation-supported-research-past-eleven': string;
      'foundation-supported-research-past-eleven-description': string;
      'foundation-supported-research-past-twelve': string;
      'foundation-supported-research-past-twelve-description': string;
      'foundation-supported-research-past-thirteen': string;
      'foundation-supported-research-past-thirteen-description': string;
    };
    'cardio-pulmonary-resuscitation': {
      title: string;
      description: string;
    };
    'friends-of-the-foundation': {
      title: string;
      description: string;
    };
    'how-you-can-help': {
      title: string;
      donation: string;
      'donation-description': string;
      'sponsoring-a-fellowship': string;
      'sponsoring-a-fellowship-description': string;
      'sponsoring-research-projects': string;
      'sponsoring-research-projects-description': string;
      'sponsoring-printing': string;
      'sponsoring-printing-description': string;
      'tax-benefits': string;
      'tax-benefits-description': string;
      'tax-exempted': string;
      'donation-form': string;
    };
    'you-can-make-a-difference': {
      title: string;
      'reduce-your-own-risk': string;
      'reduce-your-own-risk-description': string;
      'donation-to-the-foundation': string;
      'donation-to-the-foundation-description': string;
      'become-a-friend': string;
      'become-a-friend-description': string;
      'leave-a-bequest': string;
      'leave-a-bequest-description': string;
      'make-an-in-memoriam-gift': string;
      'make-an-in-memoriam-gift-description': string;
      'to-join': string;
    };
    'hall-rental': {
      title: string;
      'hall-rental-rate': string;
      items: string;
      hall: string;
      chairs: string;
      'round-tables': string;
      'pa-system': string;
      amount: string;
      deposit: string;
      'per-day': string;
      'deposit-refund': string;
      time: string;
      'care-taker': string;
      persons: string;
      cleaner: string;
      'food-catering': string;
      confirmation: string;
      'other-facilities': string;
      'rental-of-dormitory': string;
      'per-bed': string;
      beds: string;
      'rental-rooms-with-fan': string;
      'rental-rooms-with-air-cond': string;
    };
    'how-does-human-heart-works': {
      title: string;
      description: string;
      'tricuspid-valve': string;
      'tricuspid-valve-description': string;
      'pulmonary-valve': string;
      'pulmonary-valve-description': string;
      'mitral-valve': string;
      'mitral-valve-description': string;
      'aortic-valve': string;
      'aortic-valve-description': string;
      'heart-valve-description': string;
      'coronary-artery-disease': string;
      'coronary-artery-disease-description': string;
      'what-controls-the-heart-rate': string;
    };
    'four-ways-to-prevent-heart-attack': {
      title: string;
      description: string;
      'dont-smoke': string;
      'dont-smoke-description': string;
      'diet-to-keep-bmi-25': string;
      'diet-to-keep-bmi-25-description': string;
      'eat-more-fruits-vegetables': string;
      'eat-more-fruits-vegetables-description': string;
      'exercise-150-mins-week': string;
      'exercise-150-mins-week-description': string;
      'heart-attack-treatment': string;
      'heart-attack-treatment-description': string;
      subdescription: string;
    };
    'heart-disease': {
      title: string;
      'risks-for-heart-blood-vessel-disease': string;
      'risks-for-heart-blood-vessel-disease-description': string;
      'fibre-is-an-important-dietary-component': string;
      'fibre-is-an-important-dietary-component-description': string;
      'why-eat-more-fibre': string;
      'why-eat-more-fibre-description': string;
    };
    'how-does-exercise-impact-weight-loss': {
      title: string;
      description: string;
      'starting-body-weight': string;
      'starting-body-weight-description': string;
      'basal-metabolic-rate': string;
      'basal-metabolic-rate-description': string;
      'physical-activity': string;
      'physical-activity-description': string;
      subdescription: string;
    };
    'heart-bassics': {
      title: string;
      'what-is-heart-attack': string;
      'what-is-heart-attack-description': string;
      'what-is-angina': string;
      'what-is-angina-description': string;
      'what-is-silent-ischemia': string;
      'what-is-silent-ischemia-description': string;
      'what-is-heart-collateral-circulation': string;
      'what-is-heart-collateral-circulation-description': string;
      'what-are-arrhythmias': string;
      'what-are-arrhythmias-description': string;
      'what-is-sudden-cardiac-death': string;
      'what-is-sudden-cardiac-death-description': string;
      'what-is-stroke': string;
      'what-is-stroke-description': string;
      'what-is-rheumatic-heart-disease': string;
      'what-is-rheumatic-heart-disease-description': string;
      'what-is-congestive-heart-failure': string;
      'what-is-congestive-heart-failure-description': string;
      'what-is-kawasaki-disease': string;
      'what-is-kawasaki-disease-description': string;
      'what-is-bacterial-endocarditis': string;
      'what-is-bacterial-endocarditis-description': string;
      'excerpts-and-additional-information': string;
      'excerpts-and-additional-information-description': string;
    };
    'steps-to-better-health': {
      title: string;
      description: string;
      'start-now': string;
      'start-now-description': string;
      'get-moving': string;
      'get-moving-description': string;
      'lose-wisely': string;
      'lose-wisely-description': string;
      participate: string;
      'participate-description': string;
      'exercise-regularly': string;
      'exercise-regularly-description': string;
      'weigh-yourself-monthly': string;
      'weigh-yourself-monthly-description': string;
      'be-active': string;
      'be-active-description': string;
      'eat-right': string;
      'eat-right-description': string;
      'avoid-crash-diets': string;
      'avoid-crash-diets-description': string;
      'minimize-the-munchies': string;
      'minimize-the-munchies-description': string;
      'remove-temptation': string;
      'remove-temptation-description': string;
      'eat-drink-and-be-healthy': string;
      'eat-drink-and-be-healthy-description': string;
      'entertain-but-dont-be-plain': string;
      'entertain-but-dont-be-plain-description': string;
      'eat-less-exercise-more': string;
      'eat-less-exercise-more-description': string;
      'dieters-delight': string;
      'dieters-delight-description': string;
      'skim-the-fat-from-your-food': string;
      'skim-the-fat-from-your-food-description': string;
      'taste-and-enjoy-food': string;
      'taste-and-enjoy-food-description': string;
      'pick-the-winning-combination': string;
      'pick-the-winning-combination-description': string;
    };
    'tobacco-and-your-health': {
      title: string;
      subtitle: string;
      description: string;
      'who-can-be-hurt-by-tobacco': string;
      'who-can-be-hurt-by-tobacco-description': string;
      'how-does-smoking-kill': string;
      'how-does-smoking-kill-description': string;
      'how-dangerous-is-it-to-start-smoking': string;
      'how-dangerous-is-it-to-start-smoking-description': string;
      'why-people-use-tobacco': string;
      'why-people-use-tobacco-description': string;
      'what-can-you-do': string;
      'what-can-you-do-description': string;
    };
    'heart-attack': {
      title: string;
      'what-is-heart-attack': string;
      'what-is-heart-attack-description': string;
      'what-are-the-symptoms-of-heart-attack': string;
      'what-are-the-symptoms-of-heart-attack-description': string;
      'how-is-heart-attack-treated': string;
      'how-is-heart-attack-treated-description': string;
      'is-there-any-way-to-reduce-the-chance-of-heart-attack': string;
      'is-there-any-way-to-reduce-the-chance-of-heart-attack-description': string;
    };
    arrhythmias: {
      title: string;
      'what-are-arrhythmias': string;
      'what-are-arrhythmias-description': string;
      'how-do-arrhythmias-occur': string;
      'how-do-arrhythmias-occur-description': string;
      'what-are-the-symptoms-of-arrhythmias': string;
      'what-are-the-symptoms-of-arrhythmias-description': string;
      'who-is-prone-to-arrhythmias': string;
      'who-is-prone-to-arrhythmias-description': string;
    };
    'inherited-cholesterol-disorder': {
      title: string;
      description: string;
      'what-is-fh': string;
      'what-is-fh-description': string;
      'how-can-fh-be-detected': string;
      'how-can-fh-be-detected-description': string;
      'fh-risks': string;
      'fh-risks-description': string;
      'how-is-fh-treated': string;
      'how-is-fh-treated-description': string;
      'drug-therapy': string;
      'drug-therapy-description': string;
      'what-is-cholesterol': string;
      'what-is-cholesterol-description': string;
      'good-and-bad-cholesterol': string;
      'good-and-bad-cholesterol-description': string;
      'your-cholesterol-reading': string;
      'your-cholesterol-reading-description': string;
    };
    'photo-gallery': {
      title: string;
    };
    'cpr-class-regulations-and-syllabus': {
      title: string;
      subtitle: string;
      description: string;
    };
    'course-proforma': {
      title: string;
      background: string;
      'background-one': string;
      'background-two': string;
      'background-three': string;
      'aim-of-the-course': string;
      'aim-of-the-course-one': string;
      'training-strategies': string;
      'training-strategies-one': string;
      trainers: string;
      'trainers-one': string;
      assessment: string;
      'assessment-one': string;
      examiners: string;
      'examiners-one': string;
      award: string;
      'award-one': string;
      programme: string;
      'programme-one': string;
      'programme-two': string;
      'programme-three': string;
      'programme-four': string;
      'programme-five': string;
      'programme-six': string;
      'programme-seven': string;
      'programme-eight': string;
      'programme-nine': string;
      'programme-ten': string;
      'programme-eleven': string;
      'programme-twelve': string;
      'programme-thirteen': string;
      'programme-fourteen': string;
      'programme-fifteen': string;
      'programme-sixteen': string;
      'programme-seventeen': string;
      'programme-eighteen': string;
      'programme-nineteen': string;
      'programme-twenty': string;
    };
    'axa-hearts-in-action-run': {
      title: string;
      description: string;
    };
    'walk-a-million-miles': {
      title: string;
      subtitle: string;
    };
    'go-red-for-women': {
      title: string;
      description: string;
    };
  }
}
